remote_theme: "jekyll/minima@1e8a445"

minima:
  nav_pages:
  hide_site_feed_link: true
  social_links:
    - title: "Simple Docs Extractor on GitHub"
      icon: github
      url: "https://github.com/ben-shepherd/simple-docs-extractor"
  author:
    name: Ben Shepherd
    email: "ben.shepherd@gmx.com"