name: ci

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [ $default-branch, develop ]
    types: [opened, synchronize]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: "lts/*"

      - name: Setup Dependencies
        run: npm ci

  format:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: "lts/*"

      - name: Setup Dependencies
        run: npm ci

      - name: Format Check
        run: npm run format

  test:
    needs: [lint, format]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: "lts/*"

      - name: Setup Dependencies
        run: npm ci

      - name: Run Tests
        run: npm run test:coverage
