name: Formatting / Generate Docs / GitHub Pages

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    types: [closed]

jobs:
  setup:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'workflow_dispatch' || 
      (github.event_name == 'push' && github.actor != 'github-actions[bot]' && !startsWith(github.event.head_commit.message, 'docs:')) ||
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true)

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PAT }}

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: "lts/*"
  
      - name: Setup Dependencies
        run: npm ci

  formatting-checks:
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      # Other steps that change files in the repository go here
      - name: Fix Formatting
        run: npm run format

      - name: Fix Linting
        run: npm run lint:fix

      - name: Run Checks (Typecheck, TSLint, Format, Lint)
        run: npm run check

  generate-docs:
    needs: [formatting-checks]
    runs-on: ubuntu-latest
    steps:

      - name: Run Publish Docs
        run: npm run docs:publish

      # Check if there are any changes to commit
      - name: Check for changes
        id: check-changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v6
        if: steps.check-changes.outputs.changes == 'true'
        with:
          commit_message: "docs: publish documentation updates: skip-checks:true"
          file_pattern: "docs/**"
          commit_author: "GitHub Actions <actions@github.com>"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "actions@github.com"
          token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}

  configure-pages:
    needs: [generate-docs]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5