name: Generate Docs / GitHub Pages

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    types: [closed]

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PAT }}

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: "lts/*"

      - name: Setup Dependencies
        run: npm ci

      - name: Run Publish Docs
        run: npm run docs:publish

      - name: Check for changes
        id: check-changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi

      - uses: stefanzweifel/git-auto-commit-action@v6
        if: steps.check-changes.outputs.changes == 'true'
        with:
          commit_message: "docs: publish documentation updates: skip-checks:true"
          file_pattern: "docs/**"
          commit_author: "GitHub Actions <actions@github.com>"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "actions@github.com"
          token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
